# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-executables-have-shebangs
    -   id: check-added-large-files
    -   id: check-toml
    -   id: detect-private-key
    -   id: requirements-txt-fixer
    -   id: fix-encoding-pragma
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
        language_version: python3
-   repo: https://gitlab.com/pycqa/flake8
    rev: master
    hooks:
    -   id: flake8
        language_version: python3
        additional_dependencies: [mccabe, naming, pycodestyle, pyflakes]
